### ISSUE TITLE
do not start a new <frames> for toggle in caption presence

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#168]
Currently, dvrescue makes a new <frames> where there is change in the presence of captioning packs. I suggest to remove this so that:

```xml
<frames count="1493" pts="00:04:28.167900" end_pts="00:05:17.984333" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="48000" channels="2">
	<frame n="8037" pos="964440000" pts="00:04:28.167900" tc="00:04:28;08" arb="B"/>
	<frame n="9529" pos="1143480000" pts="00:05:17.950967" tc="00:05:18;02" arb="3"/>
</frames>
<frames count="193" pts="00:05:17.984333" end_pts="00:05:24.424100" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="48000" channels="2" captions="y">
	<frame n="9530" pos="1143600000" pts="00:05:17.984333" tc="00:05:18;03" arb="4"/>
	<frame n="9722" pos="1166640000" pts="00:05:24.390733" tc="00:05:24;15" arb="4"/>
</frames>
```
would become:

```xml
<frames count="1686" pts="00:04:28.167900" end_pts="00:05:24.424100" size="720x480" video_rate="30000/1001" chroma_subsampling="4:1:1" aspect_ratio="4/3" audio_rate="48000" channels="2" captions="y">
	<frame n="8037" pos="964440000" pts="00:04:28.167900" tc="00:04:28;08" arb="B"/>
	<frame n="9530" pos="1143600000" pts="00:05:17.984333" tc="00:05:18;03" arb="4" cap="end"/>
	<frame n="9722" pos="1166640000" pts="00:05:24.390733" tc="00:05:24;15" arb="4"/>
</frames>
```

Ideas on how to acknowledge the change in captioning presences? Here I had frames/@captions to indicate y or n about if the first frame includes captions, and then in frame/@cap used 'start|end' to express points where the captioning presence toggle.

**Comment by JeromeMartinez** [comment]
In your example, I understand from "current" that captions starts at the 2nd part but in your proposal it ends at the second part, difficult to follow but I think I get the idea.

Suggestion:
`frames@captions` would have a new possibility "p" (for partial)
`frame@cap` would contain "start" or "end"

In my opinion it should be an option (by default or not by default) because I consider caption presence as video/audio change, and I would put that as not by default because it is not easy to know while looking at `frame` if it has a caption or not (because info is not on the `frames` level anymore, and also not on the studied `frame`, it depends on previous instances of `frame`).

**Comment by dericed** [comment]
sounds good. frames/@captions='n' can be default so not needed to be expressed, otherwise:
'p' - partial captions with exportable data
'y' - captions with exportable data

we could also consider:
'e' - empty captions, just pack filled with 0x8080 or other non-exported values

Yes, with the new arrangement:
- if `../frames/not(@caption)` then no captions
- if `../frames/@caption='y'` then captions
- if `../frames/@caption='p'` then if `preceding-sibling::frame[1]/@cap='end'` then no captions ; else captions

**Comment by JeromeMartinez** [comment]
> 'e' - empty captions, just pack filled with 0x8080 or other non-exported values

Would be another PR, and also another attribute, as it is not exclusive (you can have "e" with either "p" or "y").
