### ISSUE TITLE
"Add Files" only finds xml

### ISSUE THREAD

**Issue by privatezero** [mipops/dvrescue#276]
Testing version `v.0.20.11.20210320` on Ubuntu 20.04 and currently something is off with the "Add Files" button in the GUI. It only allows the loading of .xml files and not .dv files.

If the "Add Files" button is not used, dragging and dropping a .dv file into the GUI seems to perform as expected.

**Comment by libbyhopfauf** [comment]
@privatezero In the Mac version, you can change the file kind it's looking for, but the default is .xml (took me a bit to see that I could change it). Is that an option on the Ubuntu end? Regardless, I was also about to post an issue regarding this. Could we make it so that the tool just searches for all compatible files?
<img width="1792" alt="Screen Shot 2021-03-24 at 4 46 58 PM" src="https://user-images.githubusercontent.com/13877631/112398084-8ea94700-8cc0-11eb-9b36-54056aa2c3eb.png">

**Comment by privatezero** [comment]
lol oops! I just found I can do the same - but yes I agree, I think it would be best if the GUI showed all possible inputs. +1 on Libby's future issue
