### ISSUE TITLE
Audio errors in AVC videocap

### ISSUE THREAD

**Issue by kelleycoyne** [mipops/dvrescue#435]
Audio seems to be recorded in wrong sample rate, either sped up or slowed down. This only effects second half of capture it seems. When recorded separately no issues, but when I try to concatenate the files, the issue returns. Attached folder contains the full take with errors and the separate takes where the audio is correct.

https://drive.google.com/drive/folders/1j-I_2XuYboMcsFWtTfUT2H1PYNuo_ACw?usp=sharing

**Comment by libbyhopfauf** [comment]
@kelleycoyne just to clarify, did you use AVC videocap to transfer this tape (vs. dvrescue capture or vrecord dvcapture)? Based purely on running the XMLs through dvrescue's analysis mode, it does appear that the audio switched from 32k to 48k at timecode 00:09:06;08 in "part2_01" and "part2_02" appears to remain consistent at 32k. For situations like this, we usually recommend packaging the file (using dvpackager) into separate files using "audio setting change" to segment the file. Most players won't be able to adjust to the change. Do you have an XML for the full file? I wasn't able to download it over my work's wifi.

**Comment by kelleycoyne** [comment]
@libbyhopfauf Thank you for your reply.  I did transfer the tape using AVC videocap. I will try using dvpackager with the "audio setting change"!!

**Comment by kelleycoyne** [comment]
I think the issue was trying to concatenate the files after using dvpackager! I didn't realize they needed to stay separate. Thank you for your help!

**Comment by libbyhopfauf** [comment]
@kelleycoyne no worries! You can also force the audio settings to be all the same and keep it as a single file, but I think that's still a feature that needs to be integrated into dvpackager. So you could end up with several files (the ones split by audio setting in their original recorded setting, plus another one that is forced to change the audio settings all to the same). If you don't select any of the segmenting rules in dvpackager, it will default to force all of the audio to a single setting. @dericed can correct me if I'm mistaken!

**Comment by dericed** [comment]
IIUC, part2_01.dv mixes 32k and 48k audio, so dvpackager will by default resample to 48k. Then part2_02.dv is all 32k so dvpackager leaves that sample rate as is. So then then you have two file at different sample rates so concatenating after packaging wouldn't work well since the audio sample rates don't match.

Currently we only resample the audio if we need to represent a single dv file with variable sample rate in a single packaged output, so with part2_02.dv (which is all 32k) we currently just leave it as is.

I suppose we could have a force-everything-to-48k option in dvpackager. Would that help in this case?

**Comment by kelleycoyne** [comment]
That would be really great, thank you!
