### ISSUE TITLE
Documentation - Format Guide Updates

### ISSUE THREAD

**Issue by libbyhopfauf** [mipops/dvrescue#531]
Here is the [information](https://docs.google.com/document/d/14JOZ0QA85jORfquSK3atHbvJjpcVDBXorkmIsHohDEU/edit?usp=sharing) that needs to be reviewed and then, once approved, added to the format guide on the website. It will also be added to a spreadsheet in the Google Drive [here](https://docs.google.com/spreadsheets/d/1BO6N3JvnISaY_x7_nk4U0WBkGpMOO8Y5oROwVM6Jl50/edit?usp=sharing). Thank you!

**Comment by libbyhopfauf** [comment]
The spreadsheet has been fulled updated, including new links for the images. It's ready for review!

**Comment by privatezero** [comment]
I've got most of the text in over [here](https://github.com/mipops/dvrescue/blob/documentation/docs/_sections/dv_formats.md) (note this is not what it looks like on the website since this is just github processing the raw markdown - the images actually render in the web version).

The images in there are the old images still - do we have web sized versions of the new images somewhere?

**Comment by libbyhopfauf** [comment]
@privatezero this looks so great!!! Yep, the new images are all linked in the spreadsheet for each format!

**Comment by privatezero** [comment]
Those images are huge! I resized them to work better with our web theme as needed - see https://github.com/mipops/dvrescue/pull/548 for PR

**Comment by libbyhopfauf** [comment]
Oh shoot sorry!!! I meant to link to the resized files!!! My bad! Thank you.
