### ISSUE TITLE
add details to capture log

### ISSUE THREAD

**Issue by dericed** [mipops/dvrescue#611]
Currently the capture log appears like:

```
File 1: auto-rewind
File 2: auto-rewind
File 3: auto-rewind
FramePos,abst,abst_r,abst_nc,tc,tc_r,tc_nc,rdt,rdt_r,rdt_nc,rec_start,rec_end,Used,Status,Comments,BlockErrors,BlockErrors_Even,IssueFixed,SourceSpeed,FrameSpeed,InputPos,OutputPos
0,38140,,,00:02:07;08,,,2005-11-05 13:14:59,,,,,0,,,0,0,0,1.0,32,0,0
1,38150,,,00:02:07;09,,,2005-11-05 13:15:00,,,,,0,,,0,0,0,1.0,32,120000,120000
2,38160,,,00:02:07;10,,,2005-11-05 13:15:00,,,,,0,,,0,0,0,1.0,32,240000,240000
3,38170,,,00:02:07;11,,,2005-11-05 13:15:00,,,,,0,,,0,0,0,1.0,32,360000,360000
```

On one hand, I'd like to remove the input list, so that the capture log could truly be a csv, but I'd also like to store other context about the capture. Curious of thoughts?

Could we add the device name of the input to the capture log as well. I suppose @deviceName could be relevant in `<media>` as well.

**Comment by JeromeMartinez** [comment]
>  I'd like to remove the input list, so that the capture log could truly be a csv

Bug fixed with https://github.com/mipops/dvrescue/pull/612.

> Could we add the device name of the input to the capture log as well. I suppose @deviceName could be relevant in <media> as well.

Proposal in https://github.com/mipops/dvrescue/pull/612.

```
<media ref="/path/to/stored.dv" fromCapture="device://6" format="DV" size="2400000">
```

> I'd also like to store other context about the capture. Curious of thoughts?

Prefer currently (for test purpose, not automation) the text output, it has more explicit information (but not 1 line per frame) and was more tested, I see several issues with the CSV output, I'll fix that.

With CSV output you get info about a rewind with the count of rewind when the merge details are provided (so the count of frames compared i.e. the count of rewinds, how frames where merged and so on), what else is missing? Maybe the outputted extra file names (start and end of rewind)?
